logger:
  level: INFO

rabbitmq:
  hostname: rabbitmq
  user: user
  password: password
  queue:
    manager: queue_manager # Responsible to send the message
    mongo: queue_mongo # Responsible to save the message

mongo:
  hostname: mongodb
  port: 27017
  database: task_management
  collection: task
